<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.P38bW4v' shared service.

return $this->privates['.service_locator.P38bW4v'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('slugify' => function (): \App\Service\Slugify {
    return ($this->privates['App\Service\Slugify'] ?? $this->privates['App\Service\Slugify'] = new \App\Service\Slugify());
}));
