<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ArticleController::delete' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController::edit' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController::index' => function () {
    return ($this->privates['.service_locator.62SZVUr'] ?? $this->load('get_ServiceLocator_62SZVUrService.php'));
}, 'App\\Controller\\ArticleController::new' => function () {
    return ($this->privates['.service_locator.P38bW4v'] ?? $this->load('get_ServiceLocator_P38bW4vService.php'));
}, 'App\\Controller\\ArticleController::show' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\CategoryController::delete' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController::edit' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController::index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController::show' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\TagController::delete' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}, 'App\\Controller\\TagController::edit' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}, 'App\\Controller\\TagController::index' => function () {
    return ($this->privates['.service_locator.Ur1lQtD'] ?? $this->load('get_ServiceLocator_Ur1lQtDService.php'));
}, 'App\\Controller\\TagController::show' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}, 'App\\Controller\\ArticleController:delete' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController:edit' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController:index' => function () {
    return ($this->privates['.service_locator.62SZVUr'] ?? $this->load('get_ServiceLocator_62SZVUrService.php'));
}, 'App\\Controller\\ArticleController:new' => function () {
    return ($this->privates['.service_locator.P38bW4v'] ?? $this->load('get_ServiceLocator_P38bW4vService.php'));
}, 'App\\Controller\\ArticleController:show' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\CategoryController:delete' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController:edit' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController:index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController:show' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\TagController:delete' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}, 'App\\Controller\\TagController:edit' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}, 'App\\Controller\\TagController:index' => function () {
    return ($this->privates['.service_locator.Ur1lQtD'] ?? $this->load('get_ServiceLocator_Ur1lQtDService.php'));
}, 'App\\Controller\\TagController:show' => function () {
    return ($this->privates['.service_locator.z2T0V0W'] ?? $this->load('get_ServiceLocator_Z2T0V0WService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
