<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1O7TZ6g' shared service.

return $this->privates['.service_locator.1O7TZ6g'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('article' => function (): \App\Entity\Article {
    return ($this->privates['.errored..service_locator.1O7TZ6g.App\Entity\Article'] ?? $this->load('getArticleService.php'));
}, 'slugify' => function (): \App\Service\Slugify {
    return ($this->privates['App\Service\Slugify'] ?? $this->privates['App\Service\Slugify'] = new \App\Service\Slugify());
}));
