<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5UbE4e\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5UbE4e/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ5UbE4e.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ5UbE4e\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQ5UbE4e\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Q5UbE4e',
    'container.build_id' => 'db046665',
    'container.build_time' => 1540827088,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5UbE4e');
