<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNqjZ9F\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNqjZ9F/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCNqjZ9F.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCNqjZ9F\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCNqjZ9F\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CNqjZ9F',
    'container.build_id' => '4a50756e',
    'container.build_time' => 1542298824,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNqjZ9F');
