<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7VJAdkD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7VJAdkD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7VJAdkD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7VJAdkD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7VJAdkD\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7VJAdkD',
    'container.build_id' => '39857879',
    'container.build_time' => 1542288195,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7VJAdkD');
